### ISSUE TITLE
map_name.txt

### ISSUE THREAD

**Issue by jrcblue** [zqzqz/AdvTrajectoryPrediction#1]
Hi there, thank you for releasing the codes. When trying to reproduce the results by the instructions, I met the error "No such file or directory: '/home/xxxx/AdvTrajectoryPrediction/prediction/dataset/../../data/nuScenes/map_name.txt' ".  It was thrown out when I ran the test.py or generate_data.py. I was wondering whether this file is missing or I need to generate it. Thanks!

**Comment by zqzqz** [comment]
Hi @jrcblue, sorry that I did not make this dependency clear in README. 

Basically, it is a generated file recording "split scene_id map_name" in each line, just for easy implementation. You can run the script [preprocessing.py](https://github.com/zqzqz/AdvTrajectoryPrediction/blob/master/data/nuScenes/preprocessing.py#L267) to generate such file, following the instruction in [README](https://github.com/zqzqz/AdvTrajectoryPrediction/tree/master/data/nuScenes). If you want to run `tranjectron_map`, you must download nuScenes dataset to access map data.

I also added the `map_name.txt` file for nuScenes v1.0 dataset in the latest master branch, in case you have difficulty running the script.

Thanks!
