### ISSUE TITLE
Do you have the plan to share the training code?

### ISSUE THREAD

**Issue by zhangxujinsh** [zqzqz/AdvTrajectoryPrediction#2]
Thanks

**Comment by shikharvashistha** [comment]
+1

specifically would like to know, how to train trajectron++ on apolloscape dataset

**Comment by zqzqz** [comment]
Sorry for not maintaining this repo for a long time. I train the models using dirty hardcodes in the original model repos, so sadly there is no clean scripts. However, I can try my best to provide instructions.

For training trajectron++ on apolloscape:
1. Change [process_data.py](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/experiments/nuScenes/process_data.py) to apolloscape version as attached. Originally the file use nuscenes API to generate intermediate data. Now the input will be apolloscape but the output should be in the similar format. As apolloscape lacks physics dynamic information like velocity and heading, some estimation is needed.

2. The [config](https://github.com/StanfordASL/Trajectron-plus-plus/blob/master/experiments/nuScenes/models/robot/config.json) of training need to be modified. Important variables are `prediction_horizon` and `maximum_history_length` determining how long the history and predicted trajectories are.

Attached [train_trajectron_on_apolloscape.zip](https://github.com/zqzqz/AdvTrajectoryPrediction/files/14501557/train_trajectron_on_apolloscape.zip)
